import { Router } from 'express';

import { GET as route_0 } from './routes/analytics.js';
import { GET as route_1 } from './routes/applications.js';
import { POST as route_2 } from './routes/applications.js';
import { GET as route_3 } from './routes/audit-logs.js';
import { POST as route_4 } from './routes/auth/login.js';
import { GET as route_5 } from './routes/candidates.js';
import { POST as route_6 } from './routes/feedback.js';
import { GET as route_7 } from './routes/forms.js';
import { POST as route_8 } from './routes/forms.js';
import { POST as route_9 } from './routes/interviews/schedule.js';
import { GET as route_10 } from './routes/interviews.js';
import { PUT as route_11 } from './routes/notifications/read.js';
import { GET as route_12 } from './routes/panels/dashboard.js';
import { POST as route_13 } from './routes/panels/members.js';
import { DELETE as route_14 } from './routes/panels/members.js';
import { GET as route_15 } from './routes/panels.js';
import { POST as route_16 } from './routes/panels.js';
import { PUT as route_17 } from './routes/panels.js';
import { DELETE as route_18 } from './routes/panels.js';
import { GET as route_19 } from './routes/recruiter/dashboard.js';
import { GET as route_20 } from './routes/users.js';
import { POST as route_21 } from './routes/users.js';
import { PUT as route_22 } from './routes/users.js';
import { DELETE as route_23 } from './routes/users.js';
export const router = Router();

router.get('/analytics', route_0);
router.get('/applications', route_1);
router.post('/applications', route_2);
router.get('/audit-logs', route_3);
router.post('/auth/login', route_4);
router.get('/candidates', route_5);
router.post('/feedback', route_6);
router.get('/forms', route_7);
router.post('/forms', route_8);
router.post('/interviews/schedule', route_9);
router.get('/interviews', route_10);
router.put('/notifications/read', route_11);
router.get('/panels/dashboard', route_12);
router.post('/panels/members', route_13);
router.delete('/panels/members', route_14);
router.get('/panels', route_15);
router.post('/panels', route_16);
router.put('/panels', route_17);
router.delete('/panels', route_18);
router.get('/recruiter/dashboard', route_19);
router.get('/users', route_20);
router.post('/users', route_21);
router.put('/users', route_22);
router.delete('/users', route_23);
